- couldn't get `pip install guidedlda` to work
- so instead, `pip install lda` and then
- paste the `guidedlda/tests/nyt.*` files into `lda/tests/`
- paste the `guidedlda/*.py` files into `lda/`

In [22]:
import numpy as np
from lda import guidedlda as glda
import lda.glda_datasets as datasets

In [25]:
X = datasets.load_data(datasets.NYT)
vocab = datasets.load_vocab(datasets.NYT)
word2id = dict((v, idx) for idx, v in enumerate(vocab))
print(X[:10])

[[0 2 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 2 ... 0 0 0]
 [2 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [27]:
seed_topic_list = [['game', 'team', 'win', 'player', 'season', 'second', 'victory'],
                   ['percent', 'company', 'market', 'price', 'sell', 'business', 'stock', 'share'],
                   ['music', 'write', 'art', 'book', 'world', 'film'],
                   ['political', 'government', 'leader', 'official', 'state', 'country',
                    'american','case', 'law', 'police', 'charge', 'officer', 'kill', 'arrest', 'lawyer']]
    
seed_topics = {}
for t_id, st in enumerate(seed_topic_list):
    for word in st:
        seed_topics[word2id[word]] = t_id

In [28]:
model = glda.GuidedLDA(n_topics=5, n_iter=100, random_state=7, refresh=20)

In [30]:
model.fit(X, seed_topics=seed_topics, seed_confidence=0.15)

INFO:lda:n_documents: 8447
INFO:lda:vocab_size: 3012
INFO:lda:n_words: 1221626
INFO:lda:n_topics: 5
INFO:lda:n_iter: 100
INFO:lda:<0> log likelihood: -11486372
INFO:lda:<20> log likelihood: -9765300
INFO:lda:<40> log likelihood: -9659651
INFO:lda:<60> log likelihood: -9622617
INFO:lda:<80> log likelihood: -9604295
INFO:lda:<99> log likelihood: -9592268


In [31]:
n_top_words = 10
topic_word = model.topic_word_
for i, topic_dist in enumerate(topic_word):
    topic_words = np.array(vocab)[np.argsort(topic_dist)][:-(n_top_words+1):-1]
    print('Topic {}: {}'.format(i, ' '.join(topic_words)))

Topic 0: game play team win season player second point start victory
Topic 1: company percent market price business sell pay plan executive buy
Topic 2: play life man music place turn book woman write thing
Topic 3: official government state political leader states issue member case country
Topic 4: school child city family problem student life program group state
